# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  test:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run: fastlane scan
  # deploy:
  #   macos:
  #     xcode: "8.3.3"
  #   steps:
  #     - checkout
  #     - deploy:
  #         name: Deploy
  #         command: fastlane release_appstore

workflows:
  version: 2
  test_release:
    jobs:
      - test
        # filters:
        #   branches:
        #     only: circle

      # - deploy:
      #     requires:
      #       test
      #     filters:
      #       branches:
      #         only: release
